[package]
name = "buttplug"
version = "4.0.3"
authors = ["Nonpolynomial Labs, LLC <kyle@nonpolynomial.com>"]
description = "Buttplug Intimate Hardware Control Library"
license = "BSD-3-Clause"
homepage = "http://buttplug.io"
repository = "https://github.com/buttplugio/buttplug-rs.git"
readme = "../README.md"
keywords = ["usb", "serial", "hardware", "bluetooth", "teledildonics"]
edition = "2018"
exclude = ["examples/**"]

[features]
# Basic features
default=["tokio-runtime", "client", "server", "serialize-json", "btleplug-manager", "websockets", "xinput-manager", "serial-manager", "lovense-dongle-manager", "lovense-connect-service-manager"]
client=[]
server=[]
serialize-json=[]
# Connectors
websockets=["serialize-json", "async-tungstenite", "native-tls"]
# Device Communication Managers
xinput-manager=["server"]
btleplug-manager=["server", "btleplug"]
serial-manager=["server", "serialport"]
lovense-dongle-manager=["server", "serialport", "hidapi"]
lovense-connect-service-manager=["reqwest"]
# Runtime managers
tokio-runtime=["tokio/rt-multi-thread", "async-tungstenite/tokio-runtime", "async-tungstenite/tokio-native-tls"]
wasm-bindgen-runtime=["wasm-bindgen", "wasm-bindgen-futures", "futures-timer/wasm-bindgen"]
dummy-runtime=[]
android-runtime=["android-utils", "jni"]
# Compiler config
unstable=[]

[dependencies]
# buttplug_derive = { path = "../buttplug_derive" }
native-tls = { version = "0.2.7", optional = true }
buttplug_derive = "0.6.2"
futures = "0.3.15"
futures-util = "0.3.15"
async-trait = "0.1.50"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_repr = "0.1.7"
uuid = { version = "0.8.2", features = ["serde"] }
url = "2.2.2"
btleplug = { version = "0.7.2", optional = true }
# btleplug = { path = "../../btleplug", optional = true}
# btleplug = { git = 'https://github.com/deviceplug/btleplug', branch = 'master', optional = true }
strum_macros = "0.21.1"
strum = "0.21.0"
once_cell = "1.8.0"
paste = "1.0.5"
lazy_static = "1.4.0"
byteorder = "1.4.3"
valico = "3.6.0"
thiserror = "1.0.25"
async-tungstenite = { version = "0.13.1", optional = true }
futures-timer = "3.0.2"
wasm-bindgen-futures = { version = "0.4.24", optional = true }
cfg-if = "1.0.0"
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.18", features = ["json"] }
dashmap = "4.0.2"
displaydoc = "0.2.1"
serialport = { version = "4.0.1", optional = true }
hidapi = { version = "1.2.6", optional = true }
wasm-bindgen = { version = "0.2.74", optional = true }
tokio = { version = "1.7.1", features = ["sync"] }
async-stream = "0.3.2"
prost = "0.7.0"
tokio-util = "0.6.7"
reqwest = { version = "0.11.3", optional = true, features = ["native-tls"] }
serde-aux = "2.2.0"
android-utils = { version = "0.1.0", optional = true }
jni = { version = "0.19.0", optional = true }

[target.'cfg(windows)'.dependencies]
rusty-xinput = "1.2.0"

[dev-dependencies]
tokio = { version = "1.7.1", features = ["io-std", "io-util", "macros"] }
tracing-log = { version = "0.1.2", features = ["env_logger"] }

[lib]
name = "buttplug"
path = "src/lib.rs"
test = true
doctest = true
doc = true

# Only build docs on one platform (linux)
[package.metadata.docs.rs]
targets = []
# Features to pass to Cargo (default: [])
features = ["default", "unstable"]

[build-dependencies]
prost-build = "0.7.0"
